server:
  port: 7070

spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      discovery:
        locator:
          #enabled: true  # default fase
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: baidu # 路由的编号
          uri: http://www.baidu.com # 路由到的目标地址 http或者https开头的走 NettyRoutingFilter直接netty转发
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/baidu
          filters:
            - StripPrefix=1 #路径跳过单词数
#        - id: order #路由的编号
#          # uri: http://localhost:7072 # 路由到的目标地址 http或者https开头的走 NettyRoutingFilter直接netty转发
#          uri: lb://order #  lb 开头 走
#          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
#            - Path=/order/{segment}
#        - id: inventory # 路由的编号
#          #uri: http://localhost:7071 # 路由到的目标地址
#          uri: lb://inventory
#          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
#            - Path=/inventory/{segment}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30 # 指示eureka客户端需要多长时间（以秒为单位）将心跳发送到eureka服务器，以指示其仍处于活动状态
  client:
    register-with-eureka: false #网关不注册自身了
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include:
          - gateway
logging:
  level:
    root: info
    reactor.netty.http.server: debug