server:
  port: 8761 # 设置 Eureka-Server 的端口

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${hostname:localhost}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  client:
    register-with-eureka: false # 不注册到 Eureka-Server，默认为 true
    fetch-registry: false # 不从 Eureka-Server 获取注册表，默认为 true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60

endpoints:
  health:
    sensitive: false